// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"

	"tik-tok-brief/service/follow/rpc/internal/logic"
	"tik-tok-brief/service/follow/rpc/internal/svc"
	"tik-tok-brief/service/follow/rpc/proto/pb"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

// 获取关注信息
func (s *FollowServer) GetFollowInfo(ctx context.Context, in *pb.GetFollowInfoReq) (*pb.GetFollowInfoResp, error) {
	l := logic.NewGetFollowInfoLogic(ctx, s.svcCtx)
	return l.GetFollowInfo(in)
}

// 获取关注列表
func (s *FollowServer) GetFollowListByUserId(ctx context.Context, in *pb.GetFollowListByUserIdReq) (*pb.GetFollowListByUserIdResp, error) {
	l := logic.NewGetFollowListByUserIdLogic(ctx, s.svcCtx)
	return l.GetFollowListByUserId(in)
}

// 获取粉丝列表
func (s *FollowServer) GetFansListByUserId(ctx context.Context, in *pb.GetFansListByUserIdReq) (*pb.GetFansListByUserIdResp, error) {
	l := logic.NewGetFansListByUserIdLogic(ctx, s.svcCtx)
	return l.GetFansListByUserId(in)
}

// 关注
func (s *FollowServer) Follow(ctx context.Context, in *pb.FollowReq) (*pb.FollowResp, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

// 取消关注
func (s *FollowServer) UnFollow(ctx context.Context, in *pb.UnFollowReq) (*pb.UnFollowResp, error) {
	l := logic.NewUnFollowLogic(ctx, s.svcCtx)
	return l.UnFollow(in)
}

// 获取好友列表
func (s *FollowServer) GetFriendsList(ctx context.Context, in *pb.GetFriendsListReq) (*pb.GetFriendsListResp, error) {
	l := logic.NewGetFriendsListLogic(ctx, s.svcCtx)
	return l.GetFriendsList(in)
}
