// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"tik-tok-brief/service/like/rpc/internal/logic"
	"tik-tok-brief/service/like/rpc/internal/svc"
	"tik-tok-brief/service/like/rpc/proto/pb"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

// 赞操作
func (s *FollowServer) Like(ctx context.Context, in *pb.LikeReq) (*pb.LikeListResp, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

// 获取点赞视频列表
func (s *FollowServer) LikeList(ctx context.Context, in *pb.LikeListReq) (*pb.LikeListResp, error) {
	l := logic.NewLikeListLogic(ctx, s.svcCtx)
	return l.LikeList(in)
}
