// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"tik-tok-brief/service/like/rpc/internal/logic"
	"tik-tok-brief/service/like/rpc/internal/svc"
	"tik-tok-brief/service/like/rpc/proto/pb"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

// 赞操作
func (s *LikeServer) Like(ctx context.Context, in *pb.LikeReq) (*pb.LikeResp, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

// 获取点赞视频列表
func (s *LikeServer) LikeList(ctx context.Context, in *pb.LikeListReq) (*pb.LikeListResp, error) {
	l := logic.NewLikeListLogic(ctx, s.svcCtx)
	return l.LikeList(in)
}

// 获取UID是否对VID点赞
func (s *LikeServer) IsLike(ctx context.Context, in *pb.IsLikeReq) (*pb.IsLikeResp, error) {
	l := logic.NewIsLikeLogic(ctx, s.svcCtx)
	return l.IsLike(in)
}
