// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package follow

import (
	"context"

	"tik-tok-brief/service/follow/rpc/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Follow                    = pb.Follow
	FollowReq                 = pb.FollowReq
	FollowResp                = pb.FollowResp
	FollowTxnReq              = pb.FollowTxnReq
	FollowTxnResp             = pb.FollowTxnResp
	GetFansListByUserIdReq    = pb.GetFansListByUserIdReq
	GetFansListByUserIdResp   = pb.GetFansListByUserIdResp
	GetFollowInfoReq          = pb.GetFollowInfoReq
	GetFollowInfoResp         = pb.GetFollowInfoResp
	GetFollowListByUserIdReq  = pb.GetFollowListByUserIdReq
	GetFollowListByUserIdResp = pb.GetFollowListByUserIdResp
	GetFriendsListReq         = pb.GetFriendsListReq
	GetFriendsListResp        = pb.GetFriendsListResp
	UnFollowReq               = pb.UnFollowReq
	UnFollowResp              = pb.UnFollowResp

	FollowZrpcClient interface {
		// 获取关注信息
		GetFollowInfo(ctx context.Context, in *GetFollowInfoReq, opts ...grpc.CallOption) (*GetFollowInfoResp, error)
		// 获取关注列表
		GetFollowListByUserId(ctx context.Context, in *GetFollowListByUserIdReq, opts ...grpc.CallOption) (*GetFollowListByUserIdResp, error)
		// 获取粉丝列表
		GetFansListByUserId(ctx context.Context, in *GetFansListByUserIdReq, opts ...grpc.CallOption) (*GetFansListByUserIdResp, error)
		// 关注
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		// 取消关注
		UnFollow(ctx context.Context, in *UnFollowReq, opts ...grpc.CallOption) (*UnFollowResp, error)
		// 获取好友列表
		GetFriendsList(ctx context.Context, in *GetFriendsListReq, opts ...grpc.CallOption) (*GetFriendsListResp, error)
		// 关注操作（事务处理）
		FollowTxn(ctx context.Context, in *FollowTxnReq, opts ...grpc.CallOption) (*FollowTxnResp, error)
		// 关注操作失败反馈
		FollowTxnRevert(ctx context.Context, in *FollowTxnReq, opts ...grpc.CallOption) (*FollowTxnResp, error)
	}

	defaultFollowZrpcClient struct {
		cli zrpc.Client
	}
)

func NewFollowZrpcClient(cli zrpc.Client) FollowZrpcClient {
	return &defaultFollowZrpcClient{
		cli: cli,
	}
}

// 获取关注信息
func (m *defaultFollowZrpcClient) GetFollowInfo(ctx context.Context, in *GetFollowInfoReq, opts ...grpc.CallOption) (*GetFollowInfoResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFollowInfo(ctx, in, opts...)
}

// 获取关注列表
func (m *defaultFollowZrpcClient) GetFollowListByUserId(ctx context.Context, in *GetFollowListByUserIdReq, opts ...grpc.CallOption) (*GetFollowListByUserIdResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFollowListByUserId(ctx, in, opts...)
}

// 获取粉丝列表
func (m *defaultFollowZrpcClient) GetFansListByUserId(ctx context.Context, in *GetFansListByUserIdReq, opts ...grpc.CallOption) (*GetFansListByUserIdResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFansListByUserId(ctx, in, opts...)
}

// 关注
func (m *defaultFollowZrpcClient) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

// 取消关注
func (m *defaultFollowZrpcClient) UnFollow(ctx context.Context, in *UnFollowReq, opts ...grpc.CallOption) (*UnFollowResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.UnFollow(ctx, in, opts...)
}

// 获取好友列表
func (m *defaultFollowZrpcClient) GetFriendsList(ctx context.Context, in *GetFriendsListReq, opts ...grpc.CallOption) (*GetFriendsListResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFriendsList(ctx, in, opts...)
}

// 关注操作（事务处理）
func (m *defaultFollowZrpcClient) FollowTxn(ctx context.Context, in *FollowTxnReq, opts ...grpc.CallOption) (*FollowTxnResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.FollowTxn(ctx, in, opts...)
}

// 关注操作失败反馈
func (m *defaultFollowZrpcClient) FollowTxnRevert(ctx context.Context, in *FollowTxnReq, opts ...grpc.CallOption) (*FollowTxnResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.FollowTxnRevert(ctx, in, opts...)
}
