# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  # 时区设置
  time_zone: Asia/Shanghai
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  # 我们自己的项目配置
  - job_name: 'tik-tok'
    static_configs:
      # 目标的采集地址
      - targets: ['video-api:9081']
        labels:
          # 自定义标签
          app: 'video-api'
          env: 'test'

      - targets: ['user-api:9080']
          labels:
            # 自定义标签
            app: 'user-api'
            env: 'test'

      - targets: ['user-rpc:9009']
          labels:
            # 自定义标签
            app: 'user-rpc'
            env: 'test'

      - targets: ['video-rpc:9092']
          labels:
            # 自定义标签
            app: 'video-rpc'
            env: 'test'

      - targets: ['like-rpc:9094']
          labels:
            # 自定义标签
            app: 'like-rpc'
            env: 'test'

      - targets: ['follow-rpc:9093']
          labels:
            # 自定义标签
            app: 'follow-rpc'
            env: 'test'

      - targets: ['file-rpc:9091']
          labels:
            # 自定义标签
            app: 'file-rpc'
            env: 'test'

      - targets: ['comment-rpc:9095']
          labels:
            # 自定义标签
            app: 'comment-rpc'
            env: 'test'

      - targets: ['chat-rpc:9096']
          labels:
            # 自定义标签
            app: 'chat-rpc'
            env: 'test'