// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package comment

import (
	"context"

	"tik-tok-brief/service/comment/rpc/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment         = pb.Comment
	CommentListReq  = pb.CommentListReq
	CommentListResp = pb.CommentListResp
	CommentReq      = pb.CommentReq
	CommentResp     = pb.CommentResp

	CommentZrpcClient interface {
		// 评论操作
		Comment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentResp, error)
		// 某视频的评论列表
		CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error)
	}

	defaultCommentZrpcClient struct {
		cli zrpc.Client
	}
)

func NewCommentZrpcClient(cli zrpc.Client) CommentZrpcClient {
	return &defaultCommentZrpcClient{
		cli: cli,
	}
}

// 评论操作
func (m *defaultCommentZrpcClient) Comment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentResp, error) {
	client := pb.NewCommentClient(m.cli.Conn())
	return client.Comment(ctx, in, opts...)
}

// 某视频的评论列表
func (m *defaultCommentZrpcClient) CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error) {
	client := pb.NewCommentClient(m.cli.Conn())
	return client.CommentList(ctx, in, opts...)
}
