// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"context"

	"tik-tok-brief/service/file/rpc/internal/logic"
	"tik-tok-brief/service/file/rpc/internal/svc"
	"tik-tok-brief/service/file/rpc/proto/pb"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServer) UploadVideoByCos(ctx context.Context, in *pb.UploadVideoByCosReq) (*pb.UploadVideoByCosResp, error) {
	l := logic.NewUploadVideoByCosLogic(ctx, s.svcCtx)
	return l.UploadVideoByCos(in)
}
