// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"tik-tok-brief/service/comment/rpc/internal/logic"
	"tik-tok-brief/service/comment/rpc/internal/svc"
	"tik-tok-brief/service/comment/rpc/proto/pb"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

// 评论操作
func (s *CommentServer) Comment(ctx context.Context, in *pb.CommentReq) (*pb.CommentResp, error) {
	l := logic.NewCommentLogic(ctx, s.svcCtx)
	return l.Comment(in)
}

// 某视频的评论列表
func (s *CommentServer) CommentList(ctx context.Context, in *pb.CommentListReq) (*pb.CommentListResp, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
