// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"tik-tok-brief/service/video/rpc/internal/logic"
	"tik-tok-brief/service/video/rpc/internal/svc"
	"tik-tok-brief/service/video/rpc/proto/pb"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

// 保存视频信息到数据库
func (s *VideoServer) SaveVideo(ctx context.Context, in *pb.SaveVideoReq) (*pb.SaveVideoResp, error) {
	l := logic.NewSaveVideoLogic(ctx, s.svcCtx)
	return l.SaveVideo(in)
}

// 查看某用户id的视频列表
func (s *VideoServer) PublishList(ctx context.Context, in *pb.PublishListReq) (*pb.PublishListResp, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}

// 视频流
func (s *VideoServer) Feed(ctx context.Context, in *pb.FeedReq) (*pb.FeedResp, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}
