// Code generated by goctl. DO NOT EDIT.
package types

type Status struct {
	StatusCode uint32 `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type User struct {
	UserID        int64  `json:"user_id"`
	UserName      string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type Video struct {
	VideoId       int64  `json:"video_id"`
	Author        User   `json:"author"`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}

type PublishReq struct {
	Title string `form:"title" validate:"required,max=100,min=1"`
	Token string `form:"token" validate:"required"`
}

type PublishResp struct {
	Status
}

type PublishListReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type PublishListResp struct {
	Status
	VideoList []Video `json:"video_list,omitempty"`
}

type FeedReq struct {
	LastTime int64  `form:"lastTime,optional"`
	Token    string `form:"token,optional"`
}

type FeedResp struct {
	Status
	VideoList []Video `json:"videoList,omitempty"`
	NextTime  int64   `json:"nextTime,omitempty"`
}
