// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package follow

import (
	"context"

	"tik-tok-brief/service/like/rpc/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Like         = pb.Like
	LikeListReq  = pb.LikeListReq
	LikeListResp = pb.LikeListResp
	LikeReq      = pb.LikeReq
	LikeResp     = pb.LikeResp

	Follow interface {
		// 赞操作
		Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeListResp, error)
		// 获取点赞视频列表
		LikeList(ctx context.Context, in *LikeListReq, opts ...grpc.CallOption) (*LikeListResp, error)
	}

	defaultFollow struct {
		cli zrpc.Client
	}
)

func NewFollow(cli zrpc.Client) Follow {
	return &defaultFollow{
		cli: cli,
	}
}

// 赞操作
func (m *defaultFollow) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeListResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

// 获取点赞视频列表
func (m *defaultFollow) LikeList(ctx context.Context, in *LikeListReq, opts ...grpc.CallOption) (*LikeListResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.LikeList(ctx, in, opts...)
}
